apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: basic-tests
spec:
  tasks:
    - name: hello
      steps:
        name: test-step
        image: alpine
        script: |
          #!/bin/sh
          echo "Hello, world!"
