apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: basic-tests
spec:
  params:
    - description: 'Application snapshot under test'
      name: SNAPSHOT
      type: string
  tasks:
    - name: provision
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/redhat-appstudio-tekton-catalog/task-eaas-provision-space:0.1-0351e1e3df028e27e43877d9ca7e646be4ff2d65
          - name: name
            value: eaas-provision-space
          - name: kind
            value: task
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: deploy
      runAfter:
        - provision
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/14rcole/flask-konflux.git"
          - name: revision
            value: main
          - name: pathInRepo
            value: ".tekton/integration/deploy.yaml"
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: serviceaccount-secret
          value: $(tasks.provision.results.secretRef)
