apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: basic-tests
spec:
  params:
    - description: 'Application snapshot under test'
      name: SNAPSHOT
      type: string
  tasks:
    - name: provision-env-with-ephemeral-namespace-local
      taskRef:
        #        resolver: bundles
        #        params:
        #          - name: bundle
        #            value: quay.io/redhat-appstudio-tekton-catalog/task-provision-env-with-ephemeral-namespace:0.1-6fa633c8d41e1f885951bfc9d74a5ee9499af79e
        #          - name: name
        #            value: provision-env-with-ephemeral-namespace
        #          - name: kind
        #            value: task
         resolver: git
         params:
          - name: url
            value: "https://github.com/14rcole/flask-konflux.git"
          - name: revision
            value: main
          - name: pathInRepo
            value: ".tekton/integration/provision-env-with-ephemeral-namespace.yaml"
      params:
        - name: RESULT
          value: SUCCESS
        - name: KONFLUXNAMESPACE
          value: $(context.pipelineRun.namespace)
        - name: PIPELINERUN_NAME
          value: $(context.pipelineRun.name)
        - name: PIPELINERUN_UID
          value: $(context.pipelineRun.uid)a
    - name: deploy
      runAfter:
        - provision-env-with-ephemeral-namespace-local
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/14rcole/flask-konflux.git"
          - name: revision
            value: main
          - name: pathInRepo
            value: ".tekton/integration/deploy.yaml"
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: serviceaccount-secret
          value: $(tasks.provision-env-with-ephemeral-namespace-local.results.secretRef)
    - name: hello
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/14rcole/flask-konflux.git"
          - name: revision
            value: main
          - name: pathInRepo
            value: ".tekton/integration/sample-task.yaml"
