apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: basic-tests
spec:
  tasks:
    - name: hello
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/14rcole/flask-konflux.git
          - name: revision
            value: main
          - name: pathInRepo
            value: .tekton/integration/sample-task.yaml
