apiVersion: v1
kind: Pod
metadata:
  name: $PODNAME
  labels:
    app: flask-konflux
spec:
  containers:
    - name: flask-konflux
      image: $COMPONENT_CONTAINER_IMAGE
      ports:
        - containerPort: 5000
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: flask-konflux-svc
#spec:
#  selector:
#    app: flask-konflux
#  ports:
#    - name: http-port
#      protocol: TCP
#      port: 5000
#      target-port: endpoint
