---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-world
spec:
  description: Hello world pipeline
  tasks:
    - name: hello
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/14rcole/flask-konflux
          - name: revision
            value: main
          - name: pathInRepo
            value: .tekton/integration/tasks/sample-task.yaml
